added kubeopenapi-jsonschema to image
switching to distroless/nodejs also fixes the standard_init_linux.go:228 error

Signed-off-by: Jared Byers <j.byers@f5.com>